# Generated by Django 2.0.7 on 2018-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigLottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.TextField(db_column='Volume', unique=True)),
                ('date', models.TextField()),
                ('no1', models.IntegerField()),
                ('no2', models.IntegerField()),
                ('no3', models.IntegerField()),
                ('no4', models.IntegerField()),
                ('no5', models.IntegerField()),
                ('no6', models.IntegerField()),
                ('special', models.IntegerField()),
            ],
            options={
                'db_table': 'Big_Lottery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyLottery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('volume', models.TextField()),
                ('date', models.TextField()),
                ('no1', models.IntegerField()),
                ('no2', models.IntegerField()),
                ('no3', models.IntegerField()),
                ('no4', models.IntegerField()),
                ('no5', models.IntegerField()),
                ('no6', models.IntegerField()),
                ('no7', models.IntegerField()),
                ('no8', models.IntegerField()),
                ('no9', models.IntegerField()),
                ('no10', models.IntegerField()),
                ('no11', models.IntegerField()),
                ('no12', models.IntegerField()),
            ],
            options={
                'db_table': 'My_Lottery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwoWin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.TextField(unique=True)),
                ('date', models.TextField()),
                ('no1', models.IntegerField()),
                ('no2', models.IntegerField()),
                ('no3', models.IntegerField()),
                ('no4', models.IntegerField()),
                ('no5', models.IntegerField()),
                ('no6', models.IntegerField()),
                ('no7', models.IntegerField()),
                ('no8', models.IntegerField()),
                ('no9', models.IntegerField()),
                ('no10', models.IntegerField()),
                ('no11', models.IntegerField()),
                ('no12', models.IntegerField()),
            ],
            options={
                'db_table': 'Two_Win',
                'managed': False,
            },
        ),
    ]
