# Generated by Django 2.1 on 2018-08-13 02:07

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_search_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('active', models.TextField()),
                ('condiction', models.TextField()),
                ('result', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='switch',
            field=models.TextField(),
            preserve_default=True,
        ),
    ]
